### ISSUE TITLE
Switch to android specific module of Dagger 2

### ISSUE THREAD

**Issue by ArazAbishov** [ArazAbishov/hexocat-android#11]

**Comment by diegoalvis** [comment]
Which modules do you wish switch to Dagger 2?

**Comment by ArazAbishov** [comment]
Dagger 2 features specific module which does some magic for android specifically: https://google.github.io/dagger/android.html. The purpose of this issue is to investigate if it is worth switching to android extension of dagger or keep using "vanilla" constructs for java.
